import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/cocktail.dart';

final cocktailProvider = StateNotifierProvider<CocktailNotifier, List<Cocktail>>((ref) {
  return CocktailNotifier();
});

class CocktailNotifier extends StateNotifier<List<Cocktail>> {
  CocktailNotifier() : super(_mockCocktails);

  void rateCocktail(String id, double userRating) {
    state = state.map((c) {
      if (c.id == id) {
        final newCount = c.ratingsCount == 0 ? 1 : c.ratingsCount + 1;
        final currentTotal = c.rating * c.ratingsCount;
        final newRating = (currentTotal + userRating) / newCount;
        return c.copyWith(rating: newRating, ratingsCount: newCount);
      }
      return c;
    }).toList();
  }

  void addCommunityCocktail(Cocktail cocktail) {
    state = [cocktail, ...state];
  }
}

// Massive Database Expansion
final _mockCocktails = <Cocktail>[
  // ═══════════════════════════════════════════
  // LEADERBOARD TOP 6 — Presentation Mock Data
  // ═══════════════════════════════════════════
  Cocktail(
    id: 'lb_1',
    name: 'İstanbul Sunset',
    description: 'Prosecco, nar şurubu ve bir tutam gül suyu ile hazırlanan büyüleyici bir kokteyl. Boğaz\'da gün batımını andırır.',
    category: 'Signature',
    prepTimeMin: 4,
    intensity: 'Hafif',
    rating: 5.0,
    fpRatio: 9.9,
    isCommunity: true,
    creatorNickname: '@BoğazBarmen',
    ratingsCount: 214,
    imagePath: 'https://images.unsplash.com/photo-1560512823-829485b8bf24?auto=format&fit=crop&w=600&q=80',
    preparation: 'Soğutulmuş bir flüt bardağına nar şurubunu ve gül suyunu koyun. Yavaşça Prosecco ile tamamlayın. Kurutulmuş gül yapraklarıyla süsleyin.',
    ingredients: [
      CocktailIngredient(name: 'Prosecco', amount: '120 ml'),
      CocktailIngredient(name: 'Grenadine', amount: '20 ml'),
      CocktailIngredient(name: 'Rose Water', amount: '5 ml'),
      CocktailIngredient(name: 'Dried Rose Petals', amount: '3 adet'),
    ],
  ),
  Cocktail(
    id: 'lb_2',
    name: 'Midnight Espresso',
    description: 'Yoğun espresso, bourbon ve bal şurubunun buluştuğu sofistike bir gece kokteyli.',
    category: 'Modern',
    prepTimeMin: 5,
    intensity: 'Güçlü',
    rating: 4.9,
    fpRatio: 9.8,
    isCommunity: true,
    creatorNickname: '@KahveCini',
    ratingsCount: 187,
    imagePath: 'https://images.unsplash.com/photo-1610889556528-9a59b9aa7b38?auto=format&fit=crop&w=600&q=80',
    preparation: 'Taze çekilmiş espressoyu soğutun. Bourbon, bal şurubu ve espressoyu buzlu shaker\'da güçlüce çalkalayın. Soğutulmuş coupe kadehe süzün. Üzerine 3 adet kahve çekirdeği yerleştirin.',
    ingredients: [
      CocktailIngredient(name: 'Bourbon', amount: '45 ml'),
      CocktailIngredient(name: 'Espresso', amount: '30 ml'),
      CocktailIngredient(name: 'Bal Şurubu', amount: '15 ml'),
      CocktailIngredient(name: 'Angostura Bitters', amount: '2 dash'),
    ],
  ),
  Cocktail(
    id: 'lb_3',
    name: 'Ege Rüzgârı',
    description: 'Gin, salatalık ve taze fesleğenin ferah birleşimi. Yaz akşamları için birebir.',
    category: 'Signature',
    prepTimeMin: 4,
    intensity: 'Orta',
    rating: 4.9,
    fpRatio: 9.7,
    isCommunity: true,
    creatorNickname: '@AkdenizRuhu',
    ratingsCount: 156,
    imagePath: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=600&q=80',
    preparation: 'Shaker\'da fesleğen yapraklarını ve salatalık dilimlerini hafifçe ezin. Gin ve misket limonu suyunu ekleyip buzla çalkalayın. Bardağa double strain ile süzün ve tonik ile tamamlayın.',
    ingredients: [
      CocktailIngredient(name: 'Gin', amount: '50 ml'),
      CocktailIngredient(name: 'Misket Limonu Suyu', amount: '20 ml'),
      CocktailIngredient(name: 'Taze Fesleğen', amount: '6 yaprak'),
      CocktailIngredient(name: 'Premium Tonik', amount: '60 ml'),
    ],
  ),
  Cocktail(
    id: 'lb_4',
    name: 'Velvet Berry Blush',
    description: 'Böğürtlen, vişne suyu ve beyaz romun kadifemsi dansı. Derin mor rengiyle göz kamaştırır.',
    category: 'Modern',
    prepTimeMin: 5,
    intensity: 'Orta',
    rating: 4.8,
    fpRatio: 9.6,
    isCommunity: true,
    creatorNickname: '@MorSimyacı',
    ratingsCount: 143,
    imagePath: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=600&q=80',
    preparation: 'Böğürtlenleri shaker\'da ezin. Beyaz rom, vişne suyu ve şeker şurubunu ekleyip bol buzla çalkalayın. Bardağa double strain ile süzün. Taze böğürtlen ve nane ile süsleyin.',
    ingredients: [
      CocktailIngredient(name: 'Beyaz Rom', amount: '50 ml'),
      CocktailIngredient(name: 'Vişne Suyu', amount: '30 ml'),
      CocktailIngredient(name: 'Böğürtlen Likörü', amount: '15 ml'),
      CocktailIngredient(name: 'Şeker Şurubu', amount: '10 ml'),
      CocktailIngredient(name: 'Taze Nane', amount: '4 yaprak'),
    ],
  ),
  Cocktail(
    id: 'lb_5',
    name: 'Golden Hour Sour',
    description: 'Mezcal, passion fruit ve agave şurubunun mükemmel dengesi. Altın saat ışığını bir kadehe sığdırır.',
    category: 'Modern',
    prepTimeMin: 5,
    intensity: 'Güçlü',
    rating: 4.8,
    fpRatio: 9.5,
    isCommunity: true,
    creatorNickname: '@DumanUstası',
    ratingsCount: 128,
    imagePath: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
    preparation: 'Mezcal, passion fruit püresi, agave şurubu ve limon suyunu shaker\'da buzsuz çalkalayın (dry shake). Buz ekleyip tekrar çalkalayın. Rocks bardağına süzün.',
    ingredients: [
      CocktailIngredient(name: 'Mezcal', amount: '50 ml'),
      CocktailIngredient(name: 'Passion Fruit Püresi', amount: '20 ml'),
      CocktailIngredient(name: 'Agave Şurubu', amount: '15 ml'),
      CocktailIngredient(name: 'Limon Suyu', amount: '20 ml'),
    ],
  ),
  Cocktail(
    id: 'lb_6',
    name: 'Anadolu Negroni',
    description: 'Klasik Negroni\'nin Türk yorumu. Nar ekşisi ve sumak ile zenginleştirilmiş.',
    category: 'Signature',
    prepTimeMin: 4,
    intensity: 'Güçlü',
    rating: 4.8,
    fpRatio: 9.4,
    isCommunity: true,
    creatorNickname: '@SarayBarmeni',
    ratingsCount: 112,
    imagePath: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80',
    preparation: 'Karıştırma bardağına buzu, rakıyı, Campari\'yi ve tatlı vermutu koyun. İyice soğuyana kadar karıştırın. Rocks bardağına süzün. Nar ekşisi gezdirip portakal kabuğu ile süsleyin.',
    ingredients: [
      CocktailIngredient(name: 'Rakı', amount: '30 ml'),
      CocktailIngredient(name: 'Campari', amount: '30 ml'),
      CocktailIngredient(name: 'Tatlı Vermut', amount: '30 ml'),
      CocktailIngredient(name: 'Nar Ekşisi', amount: '5 ml'),
    ],
  ),

  // --- KLASİKLER ---
  Cocktail(
    id: '1',
    name: 'Negroni',
    description: 'Klasik bir İtalyan aperitifi. Acı, tatlı ve güçlü.',
    category: 'Klasik',
    prepTimeMin: 3,
    intensity: 'Güçlü',
    rating: 4.9,
    fpRatio: 9.8,
    imagePath: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500',
    preparation: 'Tüm malzemeleri buz dolu bir karıştırma bardağına ekleyin. İyice soğuyana kadar karıştırın. Taze buz dolu bir rocks bardağına süzün. Portakal kabuğu ile süsleyin.',
    ingredients: [
      CocktailIngredient(name: 'Gin', amount: '30 ml'),
      CocktailIngredient(name: 'Campari', amount: '30 ml'),
      CocktailIngredient(name: 'Tatlı Vermut', amount: '30 ml'),
    ],
  ),
  Cocktail(
    id: '2',
    name: 'Margarita',
    description: 'Dünyanın en popüler tekila kokteyli. Ekşi ve serinletici.',
    category: 'Klasik',
    prepTimeMin: 4,
    intensity: 'Orta',
    rating: 4.8,
    fpRatio: 9.5,
    imagePath: 'https://images.unsplash.com/photo-1560512823-829485b8bf24?w=500',
    preparation: 'Tüm malzemeleri buz dolu bir shaker\'a ekleyin. İyice çalkalayın. Kenarı tuzlanmış veya sade bir bardağa taze buz üzerine süzün.',
    ingredients: [
      CocktailIngredient(name: 'Tekila', amount: '50 ml'),
      CocktailIngredient(name: 'Triple Sec', amount: '20 ml'),
      CocktailIngredient(name: 'Misket Limonu Suyu', amount: '15 ml'),
      CocktailIngredient(name: 'Misket Limonu', amount: '1 dilim'),
    ],
  ),
  Cocktail(
    id: '3',
    name: 'Old Fashioned',
    description: 'Viski kokteyllerinin atası. Dengeli ve derin.',
    category: 'Klasik',
    prepTimeMin: 5,
    intensity: 'Güçlü',
    rating: 4.9,
    fpRatio: 9.7,
    imagePath: 'https://images.unsplash.com/photo-1597075687490-8f673c6c17f6?w=500',
    preparation: 'Bardağın dibinde şeker şurubu ve bitteri karıştırın. Buzu ve burbonun yarısını ekleyip karıştırın. Kalan burbonu ekleyip tekrar karıştırın. Portakal kabuğu ile süsleyin.',
    ingredients: [
      CocktailIngredient(name: 'Bourbon', amount: '60 ml'),
      CocktailIngredient(name: 'Şeker Şurubu', amount: '10 ml'),
      CocktailIngredient(name: 'Angostura Bitters', amount: '2 dash'),
    ],
  ),
  Cocktail(
    id: '4',
    name: 'Mojito',
    description: 'Taze nane ve limonun mükemmel uyumu.',
    category: 'Klasik',
    prepTimeMin: 5,
    intensity: 'Hafif',
    rating: 4.7,
    fpRatio: 9.0,
    imagePath: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500',
    preparation: 'Bardağın dibinde nane ve şurubu hafifçe ezin. Misket limonu suyunu ve romu ekleyin. Bardağı kırık buzla doldurun ve soda ekleyip hafifçe karıştırın.',
    ingredients: [
      CocktailIngredient(name: 'Beyaz Rom', amount: '50 ml'),
      CocktailIngredient(name: 'Misket Limonu Suyu', amount: '20 ml'),
      CocktailIngredient(name: 'Şeker Şurubu', amount: '15 ml'),
      CocktailIngredient(name: 'Taze Nane', amount: '8 yaprak'),
      CocktailIngredient(name: 'Soda', amount: 'Top up'),
    ],
  ),
  Cocktail(
    id: '5',
    name: 'Espresso Martini',
    description: 'Zarif ve enerji verici bir akşam kokteyli.',
    category: 'Klasik',
    prepTimeMin: 4,
    intensity: 'Orta',
    rating: 4.8,
    fpRatio: 9.2,
    imagePath: 'https://images.unsplash.com/photo-1629168621183-b77da12b988f?w=500',
    preparation: 'Bütün malzemeleri buzla dolu shaker\'da güçlü bir şekilde çalkalayın. Soğutulmuş martini bardağına süzün. (Üzerinde güzel bir köpük oluşmalı)',
    ingredients: [
      CocktailIngredient(name: 'Premium Vodka', amount: '50 ml'),
      CocktailIngredient(name: 'Kahve Likörü', amount: '20 ml'),
      CocktailIngredient(name: 'Espresso', amount: '30 ml'),
      CocktailIngredient(name: 'Şeker Şurubu', amount: '10 ml'),
    ],
  ),
  Cocktail(
    id: '6',
    name: 'Whiskey Sour',
    description: 'Viski ve limonun kremamsı köpükle buluşması.',
    category: 'Klasik',
    prepTimeMin: 5,
    intensity: 'Orta',
    rating: 4.8,
    fpRatio: 9.1,
    imagePath: 'https://images.unsplash.com/photo-1574853018258-009c916ff0a6?w=500',
    preparation: 'Tüm malzemeleri önce buzsuz olarak shaker\'da sertçe çalkalayın (Dry Shake). Sonra buz ekleyip tekrar çalkalayın. Bardağa süzün.',
    ingredients: [
      CocktailIngredient(name: 'Bourbon', amount: '50 ml'),
      CocktailIngredient(name: 'Limon Suyu', amount: '25 ml'),
      CocktailIngredient(name: 'Şeker Şurubu', amount: '15 ml'),
      CocktailIngredient(name: 'Yumurtanın Akı', amount: '1 adet'),
      CocktailIngredient(name: 'Angostura Bitters', amount: '1 dash'),
    ],
  ),
  Cocktail(
    id: '7',
    name: 'Moscow Mule',
    description: 'Zencefil ve limonun keskin, ferahlatıcı kombinasyonu.',
    category: 'Klasik',
    prepTimeMin: 3,
    intensity: 'Hafif',
    rating: 4.6,
    fpRatio: 9.3,
    imagePath: 'https://images.unsplash.com/photo-1579569720610-82d8cbafe589?w=500',
    preparation: 'Bakır bir kupaya buzu, votkayı ve misket limonu suyunu ekleyin. Üzerini zencefil gazozu (Ginger Beer) ile tamamlayın.',
    ingredients: [
      CocktailIngredient(name: 'Premium Vodka', amount: '50 ml'),
      CocktailIngredient(name: 'Misket Limonu Suyu', amount: '15 ml'),
      CocktailIngredient(name: 'Ginger Beer', amount: '100 ml'),
    ],
  ),
  Cocktail(
    id: '8',
    name: 'Pina Colada',
    description: 'Tropik bir klasik. Ananas ve hindistan cevizi fırtınası.',
    category: 'Egzotik',
    isCommunity: true,
    creatorNickname: '@TikiBaba',
    ratingsCount: 89,
    prepTimeMin: 4,
    intensity: 'Hafif',
    rating: 4.5,
    fpRatio: 8.8,
    imagePath: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=500',
    preparation: 'Tüm malzemeleri blenderda buz ile birlikte pürüzsüz olana kadar karıştırın. Büyük bir bardağa dökün.',
    ingredients: [
      CocktailIngredient(name: 'Beyaz Rom', amount: '50 ml'),
      CocktailIngredient(name: 'Ananas Suyu', amount: '90 ml'),
      CocktailIngredient(name: 'Hindistan Cevizi Kreması', amount: '30 ml'),
    ],
  ),
  Cocktail(
    id: '9',
    name: 'Daiquiri',
    description: 'Mükemmel dengeye sahip, rom tabanlı zarif bir ekşi.',
    category: 'Klasik',
    prepTimeMin: 3,
    intensity: 'Orta',
    rating: 4.7,
    fpRatio: 9.1,
    imagePath: 'https://images.unsplash.com/photo-1615887023516-9bfaebcd6ab7?w=500',
    preparation: 'Malzemeleri shaker\'a alın ve çok soğuk olana dek çalkalayın. Bardağa ince süzgeç ile süzün.',
    ingredients: [
      CocktailIngredient(name: 'Beyaz Rom', amount: '50 ml'),
      CocktailIngredient(name: 'Misket Limonu Suyu', amount: '20 ml'),
      CocktailIngredient(name: 'Şeker Şurubu', amount: '10 ml'),
    ],
  ),
  Cocktail(
    id: '10',
    name: 'Aperol Spritz',
    description: 'İtalya\'nın tartışmasız öğleden sonra içkisi.',
    category: 'Klasik',
    prepTimeMin: 2,
    intensity: 'Hafif',
    rating: 4.8,
    fpRatio: 9.6,
    imagePath: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=500',
    preparation: 'Gövdeli bir şarap bardağına buz doldurun. Sırasıyla Aperol, Prosecco ve sodayı ekleyip aşağıdan yukarı tek sefer karıştırın.',
    ingredients: [
      CocktailIngredient(name: 'Aperol', amount: '60 ml'),
      CocktailIngredient(name: 'Prosecco', amount: '90 ml'),
      CocktailIngredient(name: 'Soda', amount: '30 ml'),
      CocktailIngredient(name: 'Portakal Dilimi', amount: '1 dilim'),
    ],
  ),
  Cocktail(
    id: '11',
    name: 'Cosmopolitan',
    description: 'Kızılcık suyunun muhteşem dokunuşu.',
    category: 'Modern',
    isCommunity: true,
    creatorNickname: '@ŞehirBarmeni',
    ratingsCount: 24,
    prepTimeMin: 4,
    intensity: 'Orta',
    rating: 4.6,
    fpRatio: 9.0,
    imagePath: 'https://images.unsplash.com/photo-1601006509503-b09b55502c5f?w=500',
    preparation: 'Tüm malzemeleri buzlu shaker\'da çalkalayın, martini kadehine ince süzgeç ile doldurun. Portakal yağı sıkarak süsleyin.',
    ingredients: [
      CocktailIngredient(name: 'Premium Vodka', amount: '40 ml'),
      CocktailIngredient(name: 'Triple Sec', amount: '15 ml'),
      CocktailIngredient(name: 'Kızılcık Suyu', amount: '30 ml'),
      CocktailIngredient(name: 'Misket Limonu Suyu', amount: '15 ml'),
    ],
  ),
  Cocktail(
    id: '12',
    name: 'French 75',
    description: 'Cin ve şampanyanın gösterişli dansı.',
    category: 'Klasik',
    prepTimeMin: 4,
    intensity: 'Orta',
    rating: 4.8,
    fpRatio: 9.2,
    imagePath: 'https://images.unsplash.com/photo-1606118431872-91f18e9d57a9?w=500',
    preparation: 'Cin, limon suyu ve şurubu shaker\'da bol buzla çalkalayın, flüt kadehe süzün ve üzerini Prosecco ile tamamlayın.',
    ingredients: [
      CocktailIngredient(name: 'Gin', amount: '30 ml'),
      CocktailIngredient(name: 'Limon Suyu', amount: '15 ml'),
      CocktailIngredient(name: 'Şeker Şurubu', amount: '10 ml'),
      CocktailIngredient(name: 'Prosecco', amount: 'Top up'),
    ],
  ),

  // --- MODERN & SIGNATURE ---
  Cocktail(
    id: '13',
    name: 'Penicillin',
    description: 'İsli viski, bal ve zencefilin şifa dağıtan karışımı.',
    category: 'Modern',
    isCommunity: true,
    creatorNickname: '@ŞehirBarmeni',
    ratingsCount: 24,
    prepTimeMin: 5,
    intensity: 'Güçlü',
    rating: 4.9,
    fpRatio: 8.9,
    imagePath: 'https://images.unsplash.com/photo-1595981267035-7b0419ec62c2?w=500',
    preparation: 'İsli viski haricindeki malzemeleri shakerda çalkalayın. Bardağa buza süzün. İsli viskiyi yavaşça üzerine yüzdürün (float).',
    ingredients: [
      CocktailIngredient(name: 'Bourbon', amount: '50 ml'),
      CocktailIngredient(name: 'İsli Viski', amount: '10 ml (Float)'),
      CocktailIngredient(name: 'Limon Suyu', amount: '20 ml'),
      CocktailIngredient(name: 'Zencefil Şurubu', amount: '15 ml'),
      CocktailIngredient(name: 'Bal Şurubu', amount: '10 ml'),
    ],
  ),
  Cocktail(
    id: '14',
    name: 'Basil Smash',
    description: 'Taze fesleğen ve cin fırtınası.',
    category: 'Modern',
    isCommunity: true,
    creatorNickname: '@ŞehirBarmeni',
    ratingsCount: 24,
    prepTimeMin: 4,
    intensity: 'Orta',
    rating: 4.7,
    fpRatio: 9.4,
    imagePath: 'https://images.unsplash.com/photo-1536935338788-8422ea7162df?w=500',
    preparation: 'Shaker içinde fesleğen ve limonu güçlü bir şekilde muddle yapın (ezin). Cin ve şurubu ekleyip çalkalayın, double strain (iki kez süzerek) bardağa alın.',
    ingredients: [
      CocktailIngredient(name: 'Gin', amount: '50 ml'),
      CocktailIngredient(name: 'Taze Fesleğen', amount: '10-12 yaprak'),
      CocktailIngredient(name: 'Limon Suyu', amount: '20 ml'),
      CocktailIngredient(name: 'Şeker Şurubu', amount: '15 ml'),
    ],
  ),
  Cocktail(
    id: '15',
    name: 'Bramble',
    description: 'Böğürtlenli ve meyveli modern bir cin harikası.',
    category: 'Modern',
    isCommunity: true,
    creatorNickname: '@ŞehirBarmeni',
    ratingsCount: 24,
    prepTimeMin: 4,
    intensity: 'Orta',
    rating: 4.6,
    fpRatio: 9.3,
    imagePath: 'https://images.unsplash.com/photo-1517456793572-1d8efd6dc135?w=500',
    preparation: 'Böğürtlen likörü hariç tüm malzemeleri buz dolu bardağa ekleyip karıştırın. Üzerine kırık buz koyun ve böğürtlen likörünü üzerine gezdirip (float) batmasını izleyin.',
    ingredients: [
      CocktailIngredient(name: 'Gin', amount: '40 ml'),
      CocktailIngredient(name: 'Limon Suyu', amount: '15 ml'),
      CocktailIngredient(name: 'Şeker Şurubu', amount: '10 ml'),
      CocktailIngredient(name: 'Böğürtlen Likörü', amount: '15 ml'),
    ],
  ),
  Cocktail(
    id: '16',
    name: 'Paloma',
    description: 'Tekilanın anavatanında Margarita\'dan bile daha çok içilir.',
    category: 'Klasik',
    prepTimeMin: 3,
    intensity: 'Orta',
    rating: 4.8,
    fpRatio: 9.5,
    imagePath: 'https://images.unsplash.com/photo-1542848590-e88944519961?w=500',
    preparation: 'Uzun bir bardağa taze buz koyun. Tekila, misket limonu suyu ve çok az tuzu ekleyin. Üzerini Greyfurt sodası (veya taze greyfurt suyu+soda) ile tamamlayın.',
    ingredients: [
      CocktailIngredient(name: 'Tekila', amount: '50 ml'),
      CocktailIngredient(name: 'Misket Limonu Suyu', amount: '15 ml'),
      CocktailIngredient(name: 'Greyfurt Sodası', amount: 'Top up'),
    ],
  ),
  Cocktail(
    id: '17',
    name: 'Mai Tai',
    description: 'Tiki kültürünün tartışmasız kralı.',
    category: 'Egzotik',
    isCommunity: true,
    creatorNickname: '@TikiBaba',
    ratingsCount: 89,
    prepTimeMin: 5,
    intensity: 'Güçlü',
    rating: 4.9,
    fpRatio: 9.0,
    imagePath: 'https://images.unsplash.com/photo-1594220317877-380ff9ca6526?w=500',
    preparation: 'Tüm malzemeleri buzla çalkalayın. Buzuyla beraber büyük bir tiki bardağına veya rocks bardağına dökün. Bol taze nane demetiyle süsleyin.',
    ingredients: [
      CocktailIngredient(name: 'Beyaz Rom', amount: '40 ml'),
      CocktailIngredient(name: 'Koyu Rom', amount: '20 ml'),
      CocktailIngredient(name: 'Triple Sec', amount: '15 ml'),
      CocktailIngredient(name: 'Badem Şurubu (Orgeat)', amount: '15 ml'),
      CocktailIngredient(name: 'Misket Limonu Suyu', amount: '20 ml'),
    ],
  ),
  Cocktail(
    id: '18',
    name: 'Amaretto Sour',
    description: 'Tatlı ve ekşinin badem notalarıyla buluşması.',
    category: 'Klasik',
    prepTimeMin: 4,
    intensity: 'Orta',
    rating: 4.5,
    fpRatio: 9.2,
    imagePath: 'https://images.unsplash.com/photo-1629851603572-c0cb4bc50db1?w=500',
    preparation: 'Tüm malzemeleri (yumurta akı ile) bir shaker\'a alın ve önce buzsuz, daha sonra buz ekleyerek güçlüce çalkalayın.',
    ingredients: [
      CocktailIngredient(name: 'Amaretto', amount: '50 ml'),
      CocktailIngredient(name: 'Limon Suyu', amount: '25 ml'),
      CocktailIngredient(name: 'Şeker Şurubu', amount: '5 ml'),
      CocktailIngredient(name: 'Yumurtanın Akı', amount: '1 adet'),
    ],
  ),
  Cocktail(
    id: '19',
    name: 'Bloody Mary',
    description: 'Dünyanın en popüler brunch ve hangover kokteyli.',
    category: 'Klasik',
    prepTimeMin: 6,
    intensity: 'Orta',
    rating: 4.4,
    fpRatio: 8.5,
    imagePath: 'https://images.unsplash.com/photo-1587316348911-04285b5fbbfd?w=500',
    preparation: 'Domates suyu, votka, limon, worcestershire sos, karabiber, kereviz tuzu ve acı sosu buzlu bardağa alıp "rolling" tekniği (shaker\'dan bardağa aktararak) ile karıştırın.',
    ingredients: [
      CocktailIngredient(name: 'Premium Vodka', amount: '45 ml'),
      CocktailIngredient(name: 'Domates Suyu', amount: '90 ml'),
      CocktailIngredient(name: 'Limon Suyu', amount: '15 ml'),
      CocktailIngredient(name: 'Worcestershire Sos', amount: '3 dash'),
      CocktailIngredient(name: 'Acı Sos (Tabasco)', amount: '2 dash'),
    ],
  ),
  Cocktail(
    id: '20',
    name: 'Gimlet',
    description: 'Cin ve misket limonu suyunun minimalist şiiri.',
    category: 'Klasik',
    prepTimeMin: 3,
    intensity: 'Orta',
    rating: 4.7,
    fpRatio: 9.4,
    imagePath: 'https://images.unsplash.com/photo-1662998847849-0fa4b1b8aa40?w=500',
    preparation: 'Cin, taze misket limonu suyunu ve çok az şurubu buzlu shaker\'da çok soğuk olana dek çalkalayıp süzün.',
    ingredients: [
      CocktailIngredient(name: 'Gin', amount: '60 ml'),
      CocktailIngredient(name: 'Misket Limonu Suyu', amount: '20 ml'),
      CocktailIngredient(name: 'Şeker Şurubu', amount: '10 ml'),
    ],
  ),
];
